// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/icaauth/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/ibc-go/v4/modules/apps/27-interchain-accounts/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryInterchainAccountFromAddressRequest is the request type for the Query/InterchainAccountAddress RPC
type QueryInterchainAccountFromAddressRequest struct {
	Owner        string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty" yaml:"connection_id"`
}

func (m *QueryInterchainAccountFromAddressRequest) Reset() {
	*m = QueryInterchainAccountFromAddressRequest{}
}
func (m *QueryInterchainAccountFromAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInterchainAccountFromAddressRequest) ProtoMessage()    {}
func (*QueryInterchainAccountFromAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b15af4d9855ce57, []int{0}
}
func (m *QueryInterchainAccountFromAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInterchainAccountFromAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInterchainAccountFromAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInterchainAccountFromAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInterchainAccountFromAddressRequest.Merge(m, src)
}
func (m *QueryInterchainAccountFromAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInterchainAccountFromAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInterchainAccountFromAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInterchainAccountFromAddressRequest proto.InternalMessageInfo

// QueryInterchainAccountFromAddressResponse the response type for the Query/InterchainAccountFromAddress RPC
type QueryInterchainAccountFromAddressResponse struct {
	InterchainAccountAddress string `protobuf:"bytes,1,opt,name=interchain_account_address,json=interchainAccountAddress,proto3" json:"interchain_account_address,omitempty" yaml:"interchain_account_address"`
}

func (m *QueryInterchainAccountFromAddressResponse) Reset() {
	*m = QueryInterchainAccountFromAddressResponse{}
}
func (m *QueryInterchainAccountFromAddressResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryInterchainAccountFromAddressResponse) ProtoMessage() {}
func (*QueryInterchainAccountFromAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b15af4d9855ce57, []int{1}
}
func (m *QueryInterchainAccountFromAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInterchainAccountFromAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInterchainAccountFromAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInterchainAccountFromAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInterchainAccountFromAddressResponse.Merge(m, src)
}
func (m *QueryInterchainAccountFromAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInterchainAccountFromAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInterchainAccountFromAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInterchainAccountFromAddressResponse proto.InternalMessageInfo

// QueryInterchainAccountsWithConnectionRequest is the request type for the Query/InterchainAccountsWithConnection RPC
type QueryInterchainAccountsWithConnectionRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty" yaml:"connection_id"`
}

func (m *QueryInterchainAccountsWithConnectionRequest) Reset() {
	*m = QueryInterchainAccountsWithConnectionRequest{}
}
func (m *QueryInterchainAccountsWithConnectionRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryInterchainAccountsWithConnectionRequest) ProtoMessage() {}
func (*QueryInterchainAccountsWithConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b15af4d9855ce57, []int{2}
}
func (m *QueryInterchainAccountsWithConnectionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInterchainAccountsWithConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInterchainAccountsWithConnectionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInterchainAccountsWithConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInterchainAccountsWithConnectionRequest.Merge(m, src)
}
func (m *QueryInterchainAccountsWithConnectionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInterchainAccountsWithConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInterchainAccountsWithConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInterchainAccountsWithConnectionRequest proto.InternalMessageInfo

// QueryInterchainAccountFromAddressResponse the response type for the Query/InterchainAccountsWithConnection RPC
type QueryInterchainAccountsWithConnectionResponse struct {
	InterchainAccounts []*types.RegisteredInterchainAccount `protobuf:"bytes,1,rep,name=interchain_accounts,json=interchainAccounts,proto3" json:"interchain_accounts,omitempty" yaml:"interchain_accounts"`
}

func (m *QueryInterchainAccountsWithConnectionResponse) Reset() {
	*m = QueryInterchainAccountsWithConnectionResponse{}
}
func (m *QueryInterchainAccountsWithConnectionResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryInterchainAccountsWithConnectionResponse) ProtoMessage() {}
func (*QueryInterchainAccountsWithConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b15af4d9855ce57, []int{3}
}
func (m *QueryInterchainAccountsWithConnectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInterchainAccountsWithConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInterchainAccountsWithConnectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInterchainAccountsWithConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInterchainAccountsWithConnectionResponse.Merge(m, src)
}
func (m *QueryInterchainAccountsWithConnectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInterchainAccountsWithConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInterchainAccountsWithConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInterchainAccountsWithConnectionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryInterchainAccountFromAddressRequest)(nil), "gaia.icaauth.v1.QueryInterchainAccountFromAddressRequest")
	proto.RegisterType((*QueryInterchainAccountFromAddressResponse)(nil), "gaia.icaauth.v1.QueryInterchainAccountFromAddressResponse")
	proto.RegisterType((*QueryInterchainAccountsWithConnectionRequest)(nil), "gaia.icaauth.v1.QueryInterchainAccountsWithConnectionRequest")
	proto.RegisterType((*QueryInterchainAccountsWithConnectionResponse)(nil), "gaia.icaauth.v1.QueryInterchainAccountsWithConnectionResponse")
}

func init() { proto.RegisterFile("gaia/icaauth/v1/query.proto", fileDescriptor_0b15af4d9855ce57) }

var fileDescriptor_0b15af4d9855ce57 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x6a, 0x13, 0x41,
	0x1c, 0xce, 0xb4, 0x54, 0x70, 0x54, 0x84, 0x31, 0x87, 0xb0, 0x96, 0x4d, 0x5c, 0x10, 0x22, 0x98,
	0x19, 0x52, 0x11, 0x69, 0xa1, 0x4a, 0xa2, 0x28, 0x05, 0x11, 0x5c, 0x04, 0xd1, 0x4b, 0x98, 0x4c,
	0x86, 0xcd, 0x40, 0x32, 0xb3, 0xdd, 0x99, 0x8d, 0x86, 0x52, 0x04, 0x9f, 0xa0, 0x20, 0xbe, 0x83,
	0x6f, 0x62, 0x8f, 0x05, 0x2f, 0x9e, 0x82, 0x6e, 0x3c, 0xe9, 0x2d, 0x4f, 0x20, 0xfb, 0xc7, 0xd4,
	0x66, 0xd3, 0xba, 0xf6, 0x94, 0xcc, 0x7e, 0xdf, 0xf0, 0xfd, 0xf9, 0xfd, 0x76, 0xe1, 0x75, 0x8f,
	0x0a, 0x4a, 0x04, 0xa3, 0x34, 0x34, 0x7d, 0x32, 0x6a, 0x92, 0xdd, 0x90, 0x07, 0x63, 0xec, 0x07,
	0xca, 0x28, 0x74, 0x35, 0x06, 0x71, 0x06, 0xe2, 0x51, 0xd3, 0x2a, 0x7b, 0xca, 0x53, 0x09, 0x46,
	0xe2, 0x7f, 0x29, 0xcd, 0x5a, 0xf7, 0x94, 0xf2, 0x06, 0x9c, 0x50, 0x5f, 0x10, 0x2a, 0xa5, 0x32,
	0xd4, 0x08, 0x25, 0x75, 0x86, 0xde, 0x15, 0x5d, 0x46, 0xa8, 0xef, 0x0f, 0x04, 0x4b, 0x9f, 0x13,
	0x21, 0x0d, 0x0f, 0x58, 0x9f, 0x0a, 0xd9, 0xa1, 0x8c, 0xa9, 0x50, 0x1a, 0x1d, 0x2b, 0x7b, 0x5c,
	0x72, 0x2d, 0xb2, 0x6b, 0xce, 0x3b, 0x58, 0x7f, 0x1e, 0x5b, 0xd9, 0x99, 0x93, 0x5b, 0x29, 0xf7,
	0x71, 0xa0, 0x86, 0xad, 0x5e, 0x2f, 0xe0, 0x5a, 0xbb, 0x7c, 0x37, 0xe4, 0xda, 0xa0, 0x32, 0x5c,
	0x53, 0x6f, 0x24, 0x0f, 0x2a, 0xa0, 0x06, 0xea, 0x17, 0xdd, 0xf4, 0x80, 0xb6, 0xe1, 0x15, 0xa6,
	0xa4, 0xe4, 0x2c, 0x56, 0xed, 0x88, 0x5e, 0x65, 0x25, 0x46, 0xdb, 0x95, 0xd9, 0xa4, 0x5a, 0x1e,
	0xd3, 0xe1, 0x60, 0xcb, 0x39, 0x01, 0x3b, 0xee, 0xe5, 0xe3, 0xf3, 0x4e, 0xcf, 0x39, 0x00, 0xf0,
	0x56, 0x01, 0x07, 0xda, 0x57, 0x52, 0x73, 0xc4, 0xa0, 0x95, 0x8f, 0xd5, 0xa1, 0x29, 0x2b, 0xf5,
	0xd5, 0xbe, 0x39, 0x9b, 0x54, 0x6f, 0xa4, 0xca, 0xa7, 0x73, 0x1d, 0xb7, 0x22, 0x16, 0x05, 0x33,
	0x31, 0x67, 0x08, 0x6f, 0x2f, 0x77, 0xa4, 0x5f, 0x0a, 0xd3, 0x7f, 0x38, 0x77, 0xff, 0xa7, 0x97,
	0x5c, 0x03, 0xe0, 0xbf, 0x1a, 0xf8, 0x0c, 0x60, 0xa3, 0xa0, 0x5e, 0xd6, 0xc2, 0x47, 0x00, 0xaf,
	0x2d, 0x99, 0x6e, 0x05, 0xd4, 0x56, 0xeb, 0x97, 0x36, 0x1e, 0x61, 0xd1, 0x65, 0xf8, 0xef, 0x55,
	0xc0, 0x4b, 0xc8, 0x78, 0xd4, 0xc4, 0x2e, 0xf7, 0x84, 0x36, 0x3c, 0xe0, 0xbd, 0x9c, 0x74, 0xdb,
	0x9e, 0x4d, 0xaa, 0xd6, 0x69, 0x2d, 0x6a, 0xc7, 0x45, 0xb9, 0xfa, 0xf4, 0x46, 0xb4, 0x0a, 0xd7,
	0x92, 0x24, 0xe8, 0x17, 0x80, 0xeb, 0x67, 0x0d, 0x14, 0x6d, 0xe2, 0x85, 0xa5, 0xc7, 0x45, 0xd7,
	0xd0, 0xda, 0x3a, 0xcf, 0xd5, 0xb4, 0x39, 0xe7, 0xc5, 0xfb, 0x2f, 0x3f, 0x3e, 0xac, 0x3c, 0x43,
	0x4f, 0xc9, 0xe2, 0x0b, 0x99, 0x0f, 0x49, 0x92, 0xfd, 0x26, 0x7b, 0xc9, 0xcf, 0x3e, 0x39, 0x9e,
	0x19, 0xd9, 0x3b, 0x31, 0xcf, 0x7d, 0xf4, 0x13, 0xc0, 0xda, 0xbf, 0x86, 0x87, 0xb6, 0x0b, 0xda,
	0x5e, 0xbe, 0x64, 0xd6, 0xfd, 0xf3, 0x5e, 0xcf, 0x92, 0x3f, 0x49, 0x92, 0xb7, 0xd0, 0x83, 0x02,
	0xc9, 0xf5, 0x19, 0x61, 0xdb, 0xaf, 0x0e, 0xbf, 0xdb, 0xa5, 0x4f, 0x91, 0x0d, 0x0e, 0x23, 0x1b,
	0x1c, 0x45, 0x36, 0xf8, 0x16, 0xd9, 0xe0, 0x60, 0x6a, 0x97, 0x8e, 0xa6, 0x76, 0xe9, 0xeb, 0xd4,
	0x2e, 0xbd, 0xbe, 0xe7, 0x09, 0xd3, 0x0f, 0xbb, 0x98, 0xa9, 0x21, 0xa1, 0x03, 0xd3, 0xe7, 0xb4,
	0x21, 0xb9, 0x21, 0xa2, 0xcb, 0x1a, 0x86, 0x6b, 0xd3, 0x48, 0xb4, 0xc8, 0x68, 0x93, 0xbc, 0x9d,
	0xdb, 0x30, 0x63, 0x9f, 0xeb, 0xee, 0x85, 0xe4, 0x9b, 0x74, 0xe7, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0x29, 0x58, 0xce, 0x2e, 0x05, 0x00, 0x00,
}

func (this *QueryInterchainAccountFromAddressRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryInterchainAccountFromAddressRequest)
	if !ok {
		that2, ok := that.(QueryInterchainAccountFromAddressRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.ConnectionId != that1.ConnectionId {
		return false
	}
	return true
}
func (this *QueryInterchainAccountFromAddressResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryInterchainAccountFromAddressResponse)
	if !ok {
		that2, ok := that.(QueryInterchainAccountFromAddressResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.InterchainAccountAddress != that1.InterchainAccountAddress {
		return false
	}
	return true
}
func (this *QueryInterchainAccountsWithConnectionRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryInterchainAccountsWithConnectionRequest)
	if !ok {
		that2, ok := that.(QueryInterchainAccountsWithConnectionRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ConnectionId != that1.ConnectionId {
		return false
	}
	return true
}
func (this *QueryInterchainAccountsWithConnectionResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueryInterchainAccountsWithConnectionResponse)
	if !ok {
		that2, ok := that.(QueryInterchainAccountsWithConnectionResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.InterchainAccounts) != len(that1.InterchainAccounts) {
		return false
	}
	for i := range this.InterchainAccounts {
		if !this.InterchainAccounts[i].Equal(that1.InterchainAccounts[i]) {
			return false
		}
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// QueryInterchainAccountFromAddress returns the interchain account for given owner address on a given connection
	InterchainAccountFromAddress(ctx context.Context, in *QueryInterchainAccountFromAddressRequest, opts ...grpc.CallOption) (*QueryInterchainAccountFromAddressResponse, error)
	// QueryInterchainAccountsWithConnection returns all the interchain accounts on a given connection
	InterchainAccountsWithConnection(ctx context.Context, in *QueryInterchainAccountsWithConnectionRequest, opts ...grpc.CallOption) (*QueryInterchainAccountsWithConnectionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) InterchainAccountFromAddress(ctx context.Context, in *QueryInterchainAccountFromAddressRequest, opts ...grpc.CallOption) (*QueryInterchainAccountFromAddressResponse, error) {
	out := new(QueryInterchainAccountFromAddressResponse)
	err := c.cc.Invoke(ctx, "/gaia.icaauth.v1.Query/InterchainAccountFromAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InterchainAccountsWithConnection(ctx context.Context, in *QueryInterchainAccountsWithConnectionRequest, opts ...grpc.CallOption) (*QueryInterchainAccountsWithConnectionResponse, error) {
	out := new(QueryInterchainAccountsWithConnectionResponse)
	err := c.cc.Invoke(ctx, "/gaia.icaauth.v1.Query/InterchainAccountsWithConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// QueryInterchainAccountFromAddress returns the interchain account for given owner address on a given connection
	InterchainAccountFromAddress(context.Context, *QueryInterchainAccountFromAddressRequest) (*QueryInterchainAccountFromAddressResponse, error)
	// QueryInterchainAccountsWithConnection returns all the interchain accounts on a given connection
	InterchainAccountsWithConnection(context.Context, *QueryInterchainAccountsWithConnectionRequest) (*QueryInterchainAccountsWithConnectionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) InterchainAccountFromAddress(ctx context.Context, req *QueryInterchainAccountFromAddressRequest) (*QueryInterchainAccountFromAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterchainAccountFromAddress not implemented")
}
func (*UnimplementedQueryServer) InterchainAccountsWithConnection(ctx context.Context, req *QueryInterchainAccountsWithConnectionRequest) (*QueryInterchainAccountsWithConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterchainAccountsWithConnection not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_InterchainAccountFromAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInterchainAccountFromAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InterchainAccountFromAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.icaauth.v1.Query/InterchainAccountFromAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InterchainAccountFromAddress(ctx, req.(*QueryInterchainAccountFromAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InterchainAccountsWithConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInterchainAccountsWithConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InterchainAccountsWithConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.icaauth.v1.Query/InterchainAccountsWithConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InterchainAccountsWithConnection(ctx, req.(*QueryInterchainAccountsWithConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gaia.icaauth.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InterchainAccountFromAddress",
			Handler:    _Query_InterchainAccountFromAddress_Handler,
		},
		{
			MethodName: "InterchainAccountsWithConnection",
			Handler:    _Query_InterchainAccountsWithConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaia/icaauth/v1/query.proto",
}

func (m *QueryInterchainAccountFromAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInterchainAccountFromAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInterchainAccountFromAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInterchainAccountFromAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInterchainAccountFromAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInterchainAccountFromAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InterchainAccountAddress) > 0 {
		i -= len(m.InterchainAccountAddress)
		copy(dAtA[i:], m.InterchainAccountAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.InterchainAccountAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInterchainAccountsWithConnectionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInterchainAccountsWithConnectionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInterchainAccountsWithConnectionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInterchainAccountsWithConnectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInterchainAccountsWithConnectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInterchainAccountsWithConnectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InterchainAccounts) > 0 {
		for iNdEx := len(m.InterchainAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InterchainAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryInterchainAccountFromAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInterchainAccountFromAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InterchainAccountAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInterchainAccountsWithConnectionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInterchainAccountsWithConnectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.InterchainAccounts) > 0 {
		for _, e := range m.InterchainAccounts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryInterchainAccountFromAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInterchainAccountFromAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInterchainAccountFromAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInterchainAccountFromAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInterchainAccountFromAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInterchainAccountFromAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterchainAccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InterchainAccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInterchainAccountsWithConnectionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInterchainAccountsWithConnectionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInterchainAccountsWithConnectionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInterchainAccountsWithConnectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInterchainAccountsWithConnectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInterchainAccountsWithConnectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InterchainAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InterchainAccounts = append(m.InterchainAccounts, &types.RegisteredInterchainAccount{})
			if err := m.InterchainAccounts[len(m.InterchainAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
